name: VanillaMakeRepair
favicon: null
layout_spectrum: 0.25047
typography_spectrum: 0.6031615985557437
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bd6828'
    - '#79481f'
    - '#1a160b'
    - '#c2c8df'
    - '#706e79'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
